waypoint_follower_node:
  ros__parameters:
  # Lab P109
    # waypoints: [9.7, 4.2, 0.0, 
    #             -2.8, 1.5, 0.0,
    #             -3.0, -2.8, 0.0,
    #             3.1, 3.95, 0.0,
    #             6.4, 3.75, 0.0]
  # Willow garage
    waypoints: [
                6.0, 65.5, 0.0,
                91.0, 65.0, 0.0,
                41.0, 28.0, 0.0,
                73.5, 5.3, 0.0,
                75.0, -15.0, 0.0,
                -6.0, -15.0, 0.0,
                0.0, 0.0, 0.0]